version: '3'
services:

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - integration-test
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
      - "pgadmin4_data:/var/lib/pgadmin"
    networks:
      - integration-test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
    driver: local
  pgadmin4_data:
    driver: local

networks:
  integration-test:
    driver: bridge