version: '3'
services:

  bank-database:
    image: postgres:14.1-alpine
    container_name: bank-database
    networks:
      - integration-test
    volumes:
      - "bank_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-database:
    image: mongo:latest
    container_name: user-database
    networks:
      - integration-test
    volumes:
      - "user_data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user
    healthcheck:
      test: [ "CMD-SHELL", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    volumes:
#      - "pgadmin4_data:/var/lib/pgadmin"
#    networks:
#      - integration-test
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"

volumes:
  bank_data:
    driver: local
  user_data:
    driver: local
#  pgadmin4_data:
#    driver: local

networks:
  integration-test:
    driver: bridge