spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: pgpass
  # JPA properties
  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-version: 1
    sql-migration-prefix: V_
    password: pgpass
    user: postgres
    url: jdbc:postgresql://postgres:5432/postgres
    connect-retries: 3
  jackson:
    property-naming-strategy: SNAKE_CASE
# Logger configuration
logging:
  pattern:
    console: "[%d] [%-5level] %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: info
# Server configuration
server:
  port: 8888 #set your port

---

spring:
  profiles: test

  # Database
  datasource:
    url: jdbc:h2:mem:DBNAME;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    url: "jdbc:h2:mem:DBNAME;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:flyway_init.sql'"
    user: sa
    password:
    baseline-on-migrate: true

---

profiles:
  active: development
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres